
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  create-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exists
          command: |
            aws cloudformation deploy 
            --template-file template.yml 
            --stack-name my-stack
workflows:  
  deployment:
    jobs:
      - create-infrastructure
